import { SocketProvider } from "@/contexts/SocketContext";
import type { Metadata } from "next";
import Head from "next/head";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talk to Me!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-BR">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <body className={`${rubik.className} bg-black text-white`}>
        <SocketProvider>
          {children}
        </SocketProvider> 
      </body>
    </html>
  );
}
